version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    container_name: tel_notifier
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - /app/node_modules
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
  npm:
    image: node:18
    working_dir: /app
    entrypoint: [ "npm" ]
    volumes:
      - ./:/app
#Volumes
volumes:
  dbdata:
    driver: local